# Generated by Django 5.1.4 on 2026-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=200)),
            ],
        ),
    ]
